[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0

; --- Utilisateur 1001 ---
[1001]
type=endpoint
context=entreprise
disallow=all
allow=ulaw
;auth=auth1001
aors=1001

[auth1001]
type=auth
auth_type=userpass
password=password1001
username=1001

[1001]
type=aor
max_contacts=1

; --- Utilisateur 1002 ---
[1002]
type=endpoint
context=entreprise
disallow=all
allow=ulaw
;auth=auth1002
aors=1002

[auth1002]
type=auth
auth_type=userpass
password=password1002
username=1002

[1002]
type=aor
max_contacts=1