services:
  serveur-dns:
    image: ubuntu/bind9:latest
    container_name: serveur-dns
    networks:
      reseau-services:
        ipv4_address: 120.0.33.2

  routeur-1:
    image: frrouting/frr:latest
    container_name: routeur-1
    privileged: true
    dns:
      - 120.0.33.2
    networks:
      reseau-as:
        ipv4_address: 120.0.32.1
    volumes:
      - ./configs/routeur-1/init.sh:/usr/local/bin/init_custom.sh
    entrypoint: ["/bin/sh", /usr/local/bin/init_custom.sh]
  
  routeur-entreprise-as-2:
    image: frrouting/frr:latest
    container_name: routeur-entreprise-as-2
    privileged: true
    dns:
      - 120.0.33.2
    networks:
      reseau-as:
        ipv4_address: 120.0.32.3
      reseau-entreprise-as-2:
        ipv4_address: 192.168.20.1
    volumes:
      - ./configs/routeur-entreprise-as-2/init.sh:/usr/local/bin/init_custom.sh
    entrypoint: ["/bin/sh", /usr/local/bin/init_custom.sh]

  routeur-client-as-2:
    image: frrouting/frr:latest
    container_name: routeur-client-as-2
    privileged: true
    dns:
      - 120.0.33.2
    networks:
      reseau-as:
        ipv4_address: 120.0.32.4
      reseau-client-as-2:
        ipv4_address: 192.168.30.1
    volumes:
      - ./configs/routeur-client-as-2/init.sh:/usr/local/bin/init_custom.sh
    entrypoint: ["/bin/sh", /usr/local/bin/init_custom.sh]

  routeur-entreprise-as-1:
    image: frrouting/frr:latest
    container_name: routeur-entreprise-as-1
    privileged: true
    dns:
      - 120.0.33.2
    networks:
      reseau-as:
        ipv4_address: 120.0.32.5
      reseau-entreprise-as-1:
        ipv4_address: 192.168.10.1
    volumes:
      - ./configs/routeur-entreprise-as-1/init.sh:/usr/local/bin/init_custom.sh
    entrypoint: ["/bin/sh", /usr/local/bin/init_custom.sh]

  routeur-client-as-5:
    image: frrouting/frr:latest
    container_name: routeur-client-as-5
    privileged: true
    dns:
      - 120.0.33.2
    networks:
      reseau-as:
        ipv4_address: 120.0.32.6
      reseau-client-as-5:
        ipv4_address: 192.168.40.1
    volumes:
      - ./configs/routeur-client-as-5/init.sh:/usr/local/bin/init_custom.sh
    entrypoint: ["/bin/sh", /usr/local/bin/init_custom.sh]

  routeur-as-1:
    image: frrouting/frr:latest
    container_name: routeur-as-1
    privileged: true
    dns:
      - 120.0.33.2
    networks:
      reseau-as:
        ipv4_address: 120.0.32.7
    volumes:
      - ./configs/routeur-as-1/init.sh:/usr/local/bin/init_custom.sh
    entrypoint: ["/bin/sh", /usr/local/bin/init_custom.sh]
          

  routeur-as-3:
    image: frrouting/frr:latest
    container_name: routeur-as-3
    privileged: true
    dns:
      - 120.0.33.2
    networks:
      reseau-as:
        ipv4_address: 120.0.32.8
    volumes:
      - ./configs/routeur-as-3/init.sh:/usr/local/bin/init_custom.sh
    entrypoint: ["/bin/sh", /usr/local/bin/init_custom.sh]

  routeur-as-4:
    image: frrouting/frr:latest
    container_name: routeur-as-4
    privileged: true
    dns:
      - 120.0.33.2
    networks:
      reseau-as:
        ipv4_address: 120.0.32.9
    volumes:
      - ./configs/routeur-as-4/init.sh:/usr/local/bin/init_custom.sh
    entrypoint: ["/bin/sh", /usr/local/bin/init_custom.sh]

  routeur-as-5:
    image: frrouting/frr:latest
    container_name: routeur-as-5
    privileged: true
    dns:
      - 120.0.33.2
    networks:
      reseau-as:
        ipv4_address: 120.0.32.10
    volumes:
      - ./configs/routeur-as-5/init.sh:/usr/local/bin/init_custom.sh
    entrypoint: ["/bin/sh", /usr/local/bin/init_custom.sh]
  
  routeur-services:
    image: frrouting/frr:latest
    container_name: routeur-services
    privileged: true
    dns:
      - 120.0.33.2
    networks:
      reseau-as:
        ipv4_address: 120.0.32.2
      reseau-services:
        ipv4_address: 120.0.33.1
    volumes:
      - ./configs/routeur-services/init.sh:/usr/local/bin/init_custom.sh
    entrypoint: ["/bin/sh", /usr/local/bin/init_custom.sh]

  serveur-web-public:
    image: nginx:latest
    container_name: serveur-web-public
    ports:
      - 80:80
    dns:
      - 120.0.33.2
    networks:
      reseau-services:
        ipv4_address: 120.0.33.3
    volumes:
      - ./configs/serveur-web-public/html:/usr/share/nginx/html:ro

  serveur-web-entreprise:
    image: nginx:latest
    container_name: serveur-web-entreprise
    ports:
      - 8080:80
    dns:
      - 120.0.33.2
    networks:
      reseau-services:
        ipv4_address: 120.0.33.4
    volumes:
      - ./configs/serveur-web-entreprise/html:/usr/share/nginx/html:ro

  serveur-smtp:
    image: juanluisbaptiste/postfix:latest
    container_name: serveur-smtp
    dns:
      - 120.0.33.2
    networks:
      reseau-services:
        ipv4_address: 120.0.33.5

  equipement-client-as-2:
    image: alpine:latest
    container_name: equipement-client-as-2
    dns:
      - 120.0.33.2
    networks:
      reseau-client-as-2:
        ipv4_address: 192.168.30.2
    cap_add:
      - NET_ADMIN
    volumes:
      - ./configs/equipement-client-as-2/init.sh:/usr/local/bin/init_custom.sh
    entrypoint: ["/bin/sh", /usr/local/bin/init_custom.sh]

  equipement-entreprise-as-2:
    image: alpine:latest
    container_name: equipement-entreprise-as-2
    dns:
      - 120.0.33.2
    networks:
      reseau-entreprise-as-2:
        ipv4_address: 192.168.20.2
    cap_add:
      - NET_ADMIN
    volumes:
      - ./configs/equipement-entreprise-as-2/init.sh:/usr/local/bin/init_custom.sh
    entrypoint: ["/bin/sh", /usr/local/bin/init_custom.sh]
  
  serveur-dhcp-client-as-2:
    image: networkboot/dhcpd:latest
    container_name: serveur-dhcp-client-as-2
    cap_add:
      - NET_ADMIN
    networks:
      reseau-client-as-2:
        ipv4_address: 192.168.30.3
    volumes:
      - ./configs/serveur-dhcp-client-as-2/dhcpd.conf:/data/dhcpd.conf
  
  serveur-dhcp-entreprise-as-2:
    image: networkboot/dhcpd:latest
    container_name: serveur-dhcp-entreprise-as-2
    cap_add:
      - NET_ADMIN
    networks:
      reseau-entreprise-as-2:
        ipv4_address: 192.168.20.3
    volumes:
      - ./configs/serveur-dhcp-entreprise-as-2/dhcpd.conf:/data/dhcpd.conf



networks:
  reseau-as:
    driver: bridge
    ipam:
      config:
        - subnet: 120.0.32.0/24
          gateway: 120.0.32.254
  reseau-services:
    driver: bridge
    ipam:
      config:
        - subnet: 120.0.33.0/28
          gateway: 120.0.33.14
  reseau-client-as-5:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.40.0/24
          gateway: 192.168.40.254
  reseau-client-as-2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.30.0/24
          gateway: 192.168.30.254
  reseau-entreprise-as-2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
          gateway: 192.168.20.254
  reseau-entreprise-as-1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.254