services:
  router-1:
    image: frrouting/frr:latest
    container_name: router-1
    privileged: true
    networks: 
      reseau-as:
        ipv4_address: 120.0.32.1

  router-services:
    image: frrouting/frr:latest
    container_name: router-services
    privileged: true
    networks:
      reseau-as:
        ipv4_address: 120.0.32.2
      reseau-services:
        ipv4_address: 120.0.33.1

  router-as-1:
    image: frrouting/frr:latest
    container_name: router-as-1
    privileged: true
    volumes:
      - ./configs/router-as-1:/etc/frr
    networks:
      reseau-as:
        ipv4_address: 120.0.32.7

  server-dns:
    image: ubuntu/bind9:latest
    container_name: server-dns
    networks:
      reseau-services: 
        ipv4_address: 120.0.33.2
    volumes:
      - ./configs/server-dns:/etc/bind
    ports:
      - "53:53/udp"
      - "53:53/tcp"

  server-web-public:
    image: nginx:latest
    container_name: serveur-web-public
    networks:
      reseau-services:
        ipv4_address: 120.0.33.3
    ports:
      - "8080:80"
    volumes:
      - ./configs/server-web-public/html:/usr/share/nginx/html:ro
      - ./configs/server-web-public/config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped
      
  server-web-entreprise:
    image: nginx:latest
    container_name: server-web-entreprise
    networks:
      reseau-services:
        ipv4_address: 120.0.33.4
    ports:
      - "80:80"
    volumes:
      - ./configs/server-web-entreprise/html:/usr/share/nginx/html:ro
      - ./configs/server-web-entreprise/config/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: unless-stopped

networks:
  reseau-as:
    driver: bridge
    ipam:
      config:
        - subnet: 120.0.32.0/24
          gateway: 120.0.32.254
  reseau-services:
    driver: bridge
    ipam:
      config:
        - subnet: 120.0.33.0/28
          gateway: 120.0.33.14
  reseau-client-as-5:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.40.0/24
          gateway: 192.168.40.254
  reseau-client-as-2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.30.0/24
          gateway: 192.168.30.254
  reseau-entreprise-as-2:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.20.0/24
          gateway: 192.168.20.254
  reseau-entreprise-as-1:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.10.0/24
          gateway: 192.168.10.254
