frr version 8.1
frr defaults traditional
hostname routeur-as-5
log syslog informational
no ipv6 forwarding
!
interface eth0
 ip ospf area 0
!
router ospf
 ospf router-id 10.10.10.10
 network 120.0.16.0/24 area 0
!
line vty
!
