frr version 8.1
frr defaults traditional
hostname routeur-entreprise-as-1
log syslog informational
no ipv6 forwarding
!
interface eth0
 ip ospf area 0
!
interface eth1
 ip ospf area 0
!
router ospf
 ospf router-id 5.5.5.5
 network 120.0.16.0/24 area 0
 network 192.168.10.0/24 area 0
!
line vty
!
