frr version 8.1
frr defaults traditional
hostname routeur-as-3
log syslog informational
no ipv6 forwarding
!
interface eth0
 ip ospf area 0
!
router ospf
 ospf router-id 8.8.8.8
 network 120.0.16.0/24 area 0
!
line vty
!
