frr version 8.1
frr defaults traditional
hostname routeur-entreprise-as-2
log syslog informational
no ipv6 forwarding
!
interface eth0
 ip ospf area 0
!
interface eth1
 ip ospf area 0
!
interface eth2
 ip ospf area 0
!
interface eth3
 ip ospf area 0
!
router ospf
 ospf router-id 3.3.3.3
 network 120.0.16.0/24 area 0
 network 192.168.21.0/26 area 0
 network 192.168.22.64/26 area 0
 network 192.168.23.128/26 area 0
!
line vty
!
