frr version 8.1
frr defaults traditional
hostname routeur-services
log syslog informational
no ipv6 forwarding
!
interface eth0
 ip ospf area 0
!
interface eth1
 ip ospf area 0
!
router ospf
 ospf router-id 2.2.2.2
 network 120.0.16.0/24 area 0
 network 120.0.17.0/28 area 0
!
line vty
!
